config/routes.rb
Pdxpatrol::Application.routes.draw do
  resources :neighborhoods, :only => [:index, :show] do
    resources :crimes, :only => [:index, :show]
  end
  
  resources :crimes, :only => [:index, :show]

  resources :offenses, :only => [:index, :show] do
    get 'recurring_neighborhoods'
    get 'history'
  end

  resources :routes, :only => [:index, :show] do
  end
  
  get '/routes/type/:type', :to => 'routes#type'
  
  get '/trends', :to => 'trends#index'
  get '/stops/:type', :to => 'stops#index'
  # get '/'
  #get '/routes/:type', :to => 'routes#index'
  get '/about', :to => 'site#about'
  
  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
    # resources :products do
    #   member do
    #     get 'short'
    #     post 'toggle'
    #   end
    #   
    #   collection do
    #     get 'sold'
    #   end
    # end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "crimes#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  caches_page :index, :type
  
  def index
    @sc_routes = TransitRoute.streetcar_routes.all
    @max_routes = TransitRoute.max_routes.all
    @bus_routes = TransitRoute.bus_routes.all
  end
  
  def type
    respond_to do |wants|
      wants.html {}
      wants.geojson do
        case params[:type].to_sym
          when :max       then routes = TransitRoute.max_routes.all
          when :streetcar then routes = TransitRoute.streetcar_routes.all
          when :rail      then routes = TransitRoute.rail_routes.all
        end
        
        render :geojson => routes
      end
    end
  end
  
  def show
    @route  = TransitRoute.find(params[:id])
    @route2 = TransitRoute.first(:rte => @route.rte, :id.ne => @route.id)
    @routes = [@route, @route2].sort_by(&:dir)
    @stops = @route.stops
  end
end

app/helpers/routes_helper.rb
module RoutesHelper

end

app/views/routes/index.html.erb
<% title 'MAX, Street car and Bus Route Crime' %>

<div class="box rte-group">
  <header><h1>Portland Streetcar Routes</h1></header>
  <table class="routes">
    <% @sc_routes.group_by(&:rte).each do |rte, routes| %>
    <tr>
      <th><%= routes.first.desc -%></th>
      <%- routes.sort_by(&:dir).each do |rt| -%>
      <td>
        <% link_to route_path(rt) do %>
          <% if rt.dir == 0 %><span class="glyph">[</span><% end %>
          <%= rt.dir_desc.gsub(/To/, 'to') %>
          <% if rt.dir == 1 %><span class="glyph">]</span><%- end %>
        <% end %>
      </td>
      <%- end -%>
    </tr>
    <%- end -%>
  </table>
</div>

<div class="box rte-group">
  <header><h1>Trimet MAX Routes</h1></header>
  <table class="routes">
    <% @max_routes.group_by(&:rte).each do |rte, routes| %>
    <tr>
      <th><%= routes.first.desc -%></th>
      <%- routes.sort_by(&:dir).each do |rt| -%>
      <td>
        <% link_to route_path(rt) do %>
          <% if rt.dir == 0 %><span class="glyph">[</span><% end %>
          <%= rt.dir_desc.gsub(/To/, 'to') %>
          <% if rt.dir == 1 %><span class="glyph">]</span><%- end %>
        <% end %>
      </td>
      <%- end -%>
    </tr>
    <%- end -%>
  </table>
</div>

<div class="box rte-group">
  <header><h1>Trimet Bus Routes</h1></header>
  <table class="routes">
    <% @bus_routes.group_by(&:rte).each do |rte, routes| %>
    <tr>
      <th><span class="prte">#<%= rte %></span> <%= routes.first.desc -%></th>
      <%- routes.sort_by(&:dir).each do |rt| -%>
      <td>
        <% link_to route_path(rt) do %>
        <% if rt.dir == 0 %><span class="glyph">[</span><% end %>
        <%= rt.dir_desc.gsub(/To/, 'to') %>
        <% if rt.dir == 1 %><span class="glyph">]</span><%- end %>
        <% end %>
      </td>
      <% if routes.length == 1 %><td></td><% end %>
      <%- end -%>
    </tr>
    <%- end -%>
  </table>
</div>

app/views/routes/show.html.erb
<% title @route.name %>
<section id="main" data-id="<%= @route.id %>" class="slim">
  <div class="box" id="map">
    <header>
      <h1><%= "<span>##{@route.prte}</span>".html_safe if @route.bus? %> <%= @route.name %></h1>
      <%= link_to 'Locate', nil, :class => 'locate' %>
    </header>
    <div id="canvas"></div>
  </div>
</section>

<aside id="sbar">
  <div class="box transit">
    <h1 class="<%=  @route.type %>">
      <% if @route.bus? %>
        <span class="prte">#<%= @route.prte %></span>
      <% end %>
        <%= @route.desc %>
    </h1>
    <ul class="dirs">
      <% @routes.each do |rt| %>
      <li><%= link_to rt.dir_desc, route_path(rt) %></li>
      <% end %>
    </ul>
  </div>
  
  <div class="box txt" id="stops">
    <h1 class="<%=  @route.type %>">Stops</h1>
    <ul class="stops">
      <% @stops.each do |st| %>
      <li><%= link_to st.name, stop_path(st) %></li>
      <% end %>
    </ul>
  </div>
</aside>

app/views/routes/type.html.erb
test