config/routes.rb
Pdxpatrol::Application.routes.draw do
  resources :neighborhoods, :only => [:index, :show] do
    resources :crimes, :only => [:index, :show]
  end
  
  resources :crimes, :only => [:index, :show]

  resources :offenses, :only => [:index, :show] do
    get 'recurring_neighborhoods'
    get 'history'
  end

  resources :routes, :only => [:index, :show] do
  end
  
  get '/routes/type/:type', :to => 'routes#type'
  
  get '/trends', :to => 'trends#index'
  get '/stops/:type', :to => 'stops#index'
  # get '/'
  #get '/routes/:type', :to => 'routes#index'
  get '/about', :to => 'site#about'
  
  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
    # resources :products do
    #   member do
    #     get 'short'
    #     post 'toggle'
    #   end
    #   
    #   collection do
    #     get 'sold'
    #   end
    # end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "crimes#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/neighborhood.rb
class Neighborhood
  include MongoMapper::Document 

  key :name
  key :permalink
  key :portland, Boolean, :default => true
  key :geo, Hash
  key :properties, Hash
  
  timestamps!
  
  many :crimes
  many :demographics # For future historical demographics
  
  add_concerns :reporting
  
  # Not interested in tracking Ghresham, Beaverton, etc. crime that Portland 
  # precint responds to, but keep them around in case we need them later.
  scope :portland_only, where(:portland => true)
  
  def to_param
    permalink
  end
  
  def as_geojson(options = {})
    {
      :id => id,
      :geometry => geo,
      :properties => properties.merge(:name => name, :permalink => permalink)
    }
  end
end

app/models/neighborhood/reporting.rb
class Neighborhood
  def self.offense_totals_between(from, to = Time.now)
    
    # Build an object with all the offense types
    obj = {}
    offenses = Offense.sort([['type.order', 1], ['order', 1]]).all
    offenses.each do |off|
      obj[off.id.to_s] = 0
    end
    
    map = <<-JS
    function() {
      var obj = #{obj.to_json}
      obj[this.offense_id] = 1
      emit(this.neighborhood_id, obj)
    }
    JS
    
    red = <<-JS
      function(key, group) {
        var obj = #{obj.to_json}
        group.forEach(function(offenses) {
          for(var id in offenses) { 
            obj[id] += offenses[id]
          }
        })
        return obj
      }
    JS
 
    Crime.collection.map_reduce(map, red,
    :query => {:reported_at => {
      '$lt' => to, 
      '$gte' => from.change(:hour => 0)
    }}, :out => "neighborhood_totals_for_#{from.year}")
  end
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  caches_page :show, :index  
  def index
    @this_year_start = Time.now.beginning_of_year
    @neighborhoods = Neighborhood.portland_only.all
    
    respond_to do |wants|
      wants.html do
        totals = {}
        this_year_trends = MongoMapper.database["neighborhood_totals_for_#{@this_year_start.year}"] 
        this_year_trends.find.each do |tr|
          sum = 0
          tr['value'].each {|k, v| sum += v}
          totals[tr['_id']] = sum.to_i
        end
        
        @totals = totals
      end
      wants.geojson do
        render :geojson => @neighborhoods
      end
    end
  end
  
  def show
    @this_year_start = Time.now.beginning_of_year
    @last_year_start = @this_year_start - 1.year
    
    @offenses = Offense.sort([['type.order', 1], ['order', 1]]).all.group_by(&:type)    
    @neighborhood = Neighborhood.first(:permalink => params[:id])

    respond_to do |wants|
      wants.html do
        @crimes = @neighborhood.crimes.limit(5).sort(:reported_at => -1).all
        
        # Based on yearly trends. There is a window of a couple weeks for
        # crimes to be fully reported.
        @this_years_total = @neighborhood.crimes.between(@this_year_start, (Time.now - 2.weeks)).count
        @last_years_total = @neighborhood.crimes.between(@last_year_start, (Time.now - 2.weeks) - 1.year).count

        @this_year_trends = MongoMapper.database["neighborhood_totals_for_#{@this_year_start.year}"].find_one(:_id => @neighborhood.id)          
        @last_year_trends = MongoMapper.database["neighborhood_totals_for_#{@last_year_start.year}"].find_one(:_id => @neighborhood.id)
      end
      wants.geojson do
        geo = @neighborhood
        render :geojson => [geo]
      end
    end
  end
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
  def percent_change_from(from, to)
    direction = nil
    
    change = "%.1f" % (100 - ([from, to].min / [from, to].max * 100.0) rescue 0)
    klass = ""
    glyph = "_"
    
    if change != '0.0'
      if change != 'NaN'
        if to < from 
          klass = 'rise'
          glyph = '{'
        elsif change != '0.0'
          klass = 'fall'
          glyph = '}'
        end
      else
        change = 0.0
      end
    end
  
    span = content_tag(:span, glyph, :class => "#{klass} glyph")
    span + ' ' + content_tag(:span, "#{direction}#{change}%", :class => "#{klass} percent")
  end
end

app/views/neighborhoods/index.html.erb
<ol class="alpha-list">
  <% ('A'..'Z').each do |l| %>
  <li><%= link_to(l, "##{l}") %></li>
  <% end %>
</ol>

<div class="box wfilter" id="map">
  <header>
    <h1>Portland Area Neighborhoods</h1>
    <%= link_to 'Locate', nil, :class => 'locate' %>
  </header>
  <div id="neighborhoods-map"></div>
</div>

<section class="boxgroup">
  <% @neighborhoods.sort_by(&:name).group_by {|n| n.name[0..0] }.each do |letter, neighborhoods| %>
    <% if !letter.blank? && !neighborhoods.empty? %>
    <section class="letter-group">
      <h2 class="ltr" id="<%= letter %>"><%= letter %></h2>
      <% neighborhoods.each do |nh| %>
        <% if nh.portland? && !nh.permalink.empty? %>
          <div class="txt box summary">
            <h2>
              <%= link_to nh.name, neighborhood_path(nh) %>
              <span class="total"><%= number_with_delimiter(@totals[nh.id]) %> total crimes</span>
            </h2>
          </div>
        <% end %>
      <% end %>
      </section>
    <% end %>
  <% end %>
</section>

app/views/neighborhoods/show.html.erb
<% content_for :head do %>
  <%= auto_discovery_link_tag(:rss, neighborhood_crimes_url(@neighborhood, 'rss')) %>
<% end %>

<% title @neighborhood.name %>
<% keywords @neighborhood.name %>
<section id="main">
  <div class="box" id="map">
    <header>
      <h1><%= @neighborhood.name %> Crime Map &mdash; 7 days</h1>
      <%= link_to 'Locate', nil, :class => 'locate' %>
    </header>
    <div id="canvas" class="nhood-detail"></div>
  </div>
  <div class="box txt">
    <h1>Year-to-Date Comparison</h1>
    <% if @this_year_trends.nil? || @last_year_trends.nil? %>
    <p>It appears neighborhood statistical trends haven't been run yet.</p>
    <% else %>
    <table class="comparison">
      <thead>
        <tr>
          <th>Type</th>
          <th><%= @this_year_start.year %></th>
          <th><%= @last_year_start.year %></th>
          <th>+/-</th>
        </tr>
      </thead>
      <tbody>
        <% @offenses.each do |type, offenses| %>
        <% offenses.each do |offense| %>
        <% this_year = @this_year_trends['value'][offense.id.to_s] %>
        <% last_year = @last_year_trends['value'][offense.id.to_s] %>
      
        <tr>
          <th>
            <%= link_to offense_url(offense) do %>
            <span class="badge" data-code="<%= offense.type_code %>">E</span><%= offense.name %>
            <% end %>
          </th>
          <td><%= number_with_delimiter this_year.to_i %></td>
          <td><%= number_with_delimiter last_year.to_i %></td>
          <td><%= percent_change_from(this_year, last_year) %></td>
        </tr>
        <% end %>
        <% end %>
      </tbody>
    </table>
    <% end %>
  </div>
</section>

<aside id="sbar">
  <div class="box txt">
    <h1>
      <%=h @neighborhood.name %><g:plusone size="small"></g:plusone>  
    </h1>
    <div id="total">
      <div class="year">
        <span class="num"><%= number_with_delimiter @this_years_total %></span>
        <span class="label"><%= @this_year_start.year %> YTD Total</span>
      </div>
      <div class="year">
        <span class="num"><%= number_with_delimiter @last_years_total %></span>
        <span class="label"><%= @last_year_start.year %> YTD Total</span>
      </div>
    </div>
    <div>
      <% if @this_year_trends.nil? || @last_year_trends.nil? %>
      <p>Haven't parsed trends for this year.</p>
      <% else %>
      <table class="comparison">
        <thead>
          <tr>
            <th>Type</th>
            <th><%= @this_year_start.year %></th>
            <th><%= @last_year_start.year %></th>
            <th>+/-</th>
          </tr>
        </thead>
        <tbody>
          <% @offenses.each do |type, offenses| %>
          <% this_year_type_total = 0 %>
          <% last_year_type_total = 0 %>
          <% offenses.each do |offense| %>
            <% this_year = @this_year_trends['value'][offense.id.to_s] %>
            <% last_year = @last_year_trends['value'][offense.id.to_s] %>
            <% this_year_type_total += this_year %>
            <% last_year_type_total += last_year %>
          <% end %>
          <tr>
            <th><span class="badge" data-code="<%= type['name'].parameterize[0..1] %>">E</span><%= truncate(type['name'], :length => 12) %></th>
            <td><%= number_with_delimiter this_year_type_total.to_i %></td>
            <td><%= number_with_delimiter last_year_type_total.to_i %></td>
            <td><%= percent_change_from(this_year_type_total, last_year_type_total) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% end %>
    </div>
  </div>
  <% if @crimes && !@crimes.empty? %>
  <div class="box txt">
    <h1>Last 5 Crimes</h1>
    <ol class="crime-list">
      <% @crimes.each do |crime| %>
      <li data-code="<%= crime.code %>" class="<%= crime.at_daylight? ? 'day' : 'night'  %>">
        <h3 data-code="<%= crime.offense.type['name'].parameterize[0..1] %>">
          <%= link_to(crime.offense.name, crime) %>
          <span class="date"><%= crime.reported_at.strftime('%b %d %I:%m%p') %></span>
        </h3>
        <p><span class="district">District <%= crime.district %></span>&mdash;<%= crime.address %></p>
      </li>
      <% end %>
    </ol>
  </div>
  <% end %>
</aside>