config/routes.rb
Pdxpatrol::Application.routes.draw do
  resources :neighborhoods, :only => [:index, :show] do
    resources :crimes, :only => [:index, :show]
  end
  
  resources :crimes, :only => [:index, :show]

  resources :offenses, :only => [:index, :show] do
    get 'recurring_neighborhoods'
    get 'history'
  end

  resources :routes, :only => [:index, :show] do
  end
  
  get '/routes/type/:type', :to => 'routes#type'
  
  get '/trends', :to => 'trends#index'
  get '/stops/:type', :to => 'stops#index'
  # get '/'
  #get '/routes/:type', :to => 'routes#index'
  get '/about', :to => 'site#about'
  
  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
    # resources :products do
    #   member do
    #     get 'short'
    #     post 'toggle'
    #   end
    #   
    #   collection do
    #     get 'sold'
    #   end
    # end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => "crimes#index"

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title || 'Portland Crime' %></title>
  <meta name="keywords" content="<%= @keywords %> portland crime pdx safety neighborhood chinatown pearl downtown southwest southeast northeast northwest" />
  <meta name="description" content="Track and review all types of crimes happening across Portland, OR neighborhoods."/>
  <meta http-equiv="X-UA-Compatible" content="chrome=1" />
  <%= yield :head %>
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  
  <!--[if IE]>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/chrome-frame/1/CFInstall.min.js"></script>
  <script type="text/javascript" charset="utf-8">
    CFInstall.check();
  </script>
  <![endif]-->
  <%= include_stylesheets :core %>
  <%= include_javascripts :vendor %>
  <script src="http://cdn.jquerytools.org/1.2.5/all/jquery.tools.min.js"></script>
  <%= include_javascripts :app %>
  <%= csrf_meta_tag %>
  <script type="text/javascript">

    var _gaq = _gaq || [];
    
    <% if Rails.env == 'production' %>
    _gaq.push(['_setAccount', 'UA-7881178-3']);
    _gaq.push(['_trackPageview']);
    _gaq.push(['_setDomainName', 'none']); 
    _gaq.push(['_setAllowLinker', true]); 

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
    <% end %>
  </script>
  <script type="text/javascript" charset="utf-8">
    <%= yield :page_js %>
  </script>
</head>
<body data-path="<%= controller.controller_path %>-<%= controller.action_name %>">
  <header id="top">
    <div class="wrap">
      <div class="wrap-inner">
        <h1 id="logo"><%= link_to image_tag('/images/logo.png', :alt => 'Portland Crime logo'), root_path %></h1>
        <div id="subbar">
          <nav id="primary">
            <ul>
              <li class="home<%= selected_class :home %>"><%= link_to(root_path) { "<span>@</span> Crimes".html_safe } %></li>
              <li class="trends<%= selected_class :trends %>"><%= link_to(trends_path) { "<span>Y</span> Trends".html_safe } %></li>
              <li class="about<%= selected_class :neighborhoods %>"><%= link_to(neighborhoods_path) { "<span>H</span> Neighborhoods".html_safe } %></li>
              <li class="about<%= selected_class :about %>"><%= link_to(about_path) { "<span>i</span> About".html_safe } %></li>
            </ul>
            </nav><% if @last_import %><span class="last-import">Data Updated <%= @last_import.created_at.strftime('%A, %B %d %-I:%M %p') %></span><% end %>
        </div>        
      </div>
    </div>
  </header>
  
  <section id="content">
    <div class="wrap">
      <div class="wrap-inner">
        <%= yield %>
      </div>
    </div>
  </section>
  
  <footer>
    <div class="wrap">
      <div class="wrap-inner">
        <div class="box">Copyright &copy; 2010&ndash;2011 <a href="http://labratrevenge.com">LabRatRevenge LLC.</a></div>
      </div>
    </div>
  </footer>
    <script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
</body>
</html>